version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    networks:
      - os-dev

networks:
  os-dev:
    external: true
    name: os-dev
